[package]
name = "sshift_gpt"
version = "1.0.0"
authors = []

[addresses]
sshift_gpt_addr = "0x02033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "movement", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "movement", subdir = "aptos-move/framework/aptos-token-objects" }
AptosToken = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "movement", subdir = "aptos-move/framework/aptos-token" }

[dev-dependencies]
