[package]
name = "sshift"
version = "1.0.0"
authors = []

[addresses]
sshift_dao_addr = "0x28af3805f23612b4dfa86202a454f5144159702559aea86393ac0d50f577568d"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token" }

[dev-dependencies]
